# name: Deploy ni bos
# on:
#     push:
#         branches:
#             - main

# jobs:
#     build-and-deploy:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Checkout Code
#               uses: actions/checkout@v3

#             - name: Setup Docker BuildX
#               uses: docker/setup-buildx-action@v1

#             - name: Login to Docker hub
#               uses: docker/login-action@v1
#               with:
#                   username: ${{secrets.DOCKER_USERNAME}}
#                   password: ${{secrets.DOCKER_PASSWORD}}

#             - name: Build and Push Docker Image
#               run: |
#                   docker build \
#                       --build-arg DATABASE_URL=${{secrets.DATABASE_URL}} \
#                       --build-arg JWT_SECRET=${{secrets.JWT_SECRET}} \
#                       -t ${{secrets.DOCKER_USERNAME}}/clothing_store:latest .
#                   docker push ${{secrets.DOCKER_USERNAME}}/clothing_store:latest

#             - name: Deploy to Railway
#               run: |
#                   curl -X POST \
#                   -H "Content-Type: application/json" \
#                   -H "Authorization: Bearer ${{ secrets.RAILWAY_API_KEY }}" \
#                   -d "{\"image\": \"docker.io/${{ secrets.DOCKER_USERNAME }}/repository-name:latest\"}" \
#                   "https://api.railway.app/v1/services/e0b6edfe-8d41-47c6-8160-f49a76aa7c90/deploy"
